# Site settings
title: Deadpool's Security Blog
description: "Hi, I'm Tushar. I\'m a Musician, Magician & a nerd for Application Security. This blog is about some of the stuffs I do"
url: 'http://127.0.0.1:4000'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Tushar Adhikary'
  email: tushar.adhikary@gmail.com
  twitter_username: 0xdeadpool
  #facebook_username: joshgerdes
  #github_username:  joshgerdes
  linkedin_username:  tushar-adhikary-2a797851

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
